connector.name=clickhouse
connection-url=jdbc:ch:http://clickhouse:8123/multidb?compress=0
connection-user=default
connection-password=clickhouse
clickhouse.map-string-as-varchar=true
unsupported-type-handling=CONVERT_TO_VARCHAR
